"use client";

import { useState } from "react";
import type { LucideIcon } from "lucide-react";
import {
  FileText,
  Download,
  TrendingUp,
  Wallet,
  PieChart,
  Percent,
  Building2,
  Layers,
  FileBarChart2,
  CalendarClock,
  Loader2,
  CheckCircle2,
  Info,
} from "lucide-react";
import { PageHeader, SectionCard, StatGrid } from "@/app/components/DashboardUI";

type ReportRow = {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  lastGenerated: string;
  period: string;
};

const monthlyReports: ReportRow[] = [
  {
    id: "investment-performance",
    name: "Investment Performance Report",
    description: "Summary of your capital deployed, current value, and returns across all projects.",
    icon: TrendingUp,
    lastGenerated: "Aug 1, 2026",
    period: "Jul 2026",
  },
  {
    id: "revenue",
    name: "Revenue Report",
    description: "Gross booking revenue generated by your invested properties for the period.",
    icon: Wallet,
    lastGenerated: "Aug 1, 2026",
    period: "Jul 2026",
  },
  {
    id: "expense",
    name: "Expense Report",
    description: "Operating costs, maintenance, and overheads deducted before your distribution.",
    icon: FileBarChart2,
    lastGenerated: "Aug 1, 2026",
    period: "Jul 2026",
  },
  {
    id: "occupancy",
    name: "Occupancy Report",
    description: "Night-by-night occupancy and ADR trends for the properties you hold a stake in.",
    icon: Building2,
    lastGenerated: "Aug 1, 2026",
    period: "Jul 2026",
  },
  {
    id: "distribution",
    name: "Distribution Report",
    description: "Payout breakdown showing how your monthly revenue share was calculated and paid.",
    icon: Layers,
    lastGenerated: "Aug 1, 2026",
    period: "Jul 2026",
  },
];

const annualReports: ReportRow[] = [
  {
    id: "roi",
    name: "ROI Report",
    description: "Realised and projected return on investment against your original commitment.",
    icon: Percent,
    lastGenerated: "Jul 1, 2026",
    period: "Q2 FY26-27",
  },
  {
    id: "project-progress",
    name: "Project Progress Report",
    description: "Construction and development milestones for projects still in build-out.",
    icon: CalendarClock,
    lastGenerated: "Jul 1, 2026",
    period: "Q2 FY26-27",
  },
  {
    id: "unit-performance",
    name: "Unit Performance Report",
    description: "Per-unit ranking of revenue, occupancy, and guest ratings within each property.",
    icon: PieChart,
    lastGenerated: "Jul 1, 2026",
    period: "Q2 FY26-27",
  },
  {
    id: "annual-performance",
    name: "Annual Performance Report",
    description: "Full-year consolidated statement of performance across your entire portfolio.",
    icon: FileText,
    lastGenerated: "Apr 5, 2026",
    period: "FY 2025-26",
  },
];

function ReportRowItem({
  report,
  downloadingId,
  onDownload,
}: {
  report: ReportRow;
  downloadingId: string | null;
  onDownload: (report: ReportRow) => void;
}) {
  const Icon = report.icon;
  const isDownloading = downloadingId === report.id;

  return (
    <li className="flex flex-col sm:flex-row sm:items-center gap-4 px-5 py-4">
      <span className="w-10 h-10 rounded-xl bg-primary/10 text-primary flex items-center justify-center shrink-0">
        <Icon size={16} />
      </span>
      <div className="flex-1 min-w-0">
        <p className="text-sm font-medium text-foreground">{report.name}</p>
        <p className="text-xs text-muted mt-0.5">{report.description}</p>
      </div>
      <div className="flex items-center justify-between sm:justify-end gap-5 shrink-0">
        <div className="text-right">
          <p className="text-[11px] text-subtle">{report.period}</p>
          <p className="text-[11px] text-subtle">Generated {report.lastGenerated}</p>
        </div>
        <button
          onClick={() => onDownload(report)}
          disabled={isDownloading}
          aria-label={`Download ${report.name}`}
          className="inline-flex items-center gap-1.5 px-3.5 py-2 text-xs font-semibold bg-primary text-primary-foreground rounded-full hover:bg-primary-hover transition-colors disabled:opacity-70 disabled:cursor-wait shrink-0"
        >
          {isDownloading ? (
            <>
              <Loader2 size={13} className="animate-spin" /> Preparing
            </>
          ) : (
            <>
              <Download size={13} /> Download
            </>
          )}
        </button>
      </div>
    </li>
  );
}

export default function InvestorReportsPage() {
  const [downloadingId, setDownloadingId] = useState<string | null>(null);
  const [toast, setToast] = useState<string | null>(null);

  function handleDownload(report: ReportRow) {
    if (downloadingId) return;
    setDownloadingId(report.id);
    setToast(null);
    window.setTimeout(() => {
      setDownloadingId(null);
      setToast(`${report.name} (${report.period}) downloaded as PDF.`);
      window.setTimeout(() => setToast(null), 3500);
    }, 900);
  }

  const allReports = [...monthlyReports, ...annualReports];
  const mostRecent = allReports.reduce((latest, r) =>
    new Date(r.lastGenerated) > new Date(latest.lastGenerated) ? r : latest
  );

  return (
    <div className="space-y-8 pb-12">
      <PageHeader
        title="Reports"
        subtitle="Download performance, revenue, and distribution reports for your Dhyana investments."
      />

      <StatGrid
        stats={[
          { label: "Reports Available", value: String(allReports.length), icon: FileText },
          { label: "Most Recent", value: mostRecent.lastGenerated, icon: CalendarClock },
          { label: "Format", value: "PDF", icon: FileBarChart2 },
          { label: "Delivery", value: "Dashboard + Email", icon: Wallet },
        ]}
      />

      <SectionCard title="Monthly Reports" icon={CalendarClock}>
        <ul className="divide-y divide-surface-hover">
          {monthlyReports.map((r) => (
            <ReportRowItem key={r.id} report={r} downloadingId={downloadingId} onDownload={handleDownload} />
          ))}
        </ul>
      </SectionCard>

      <SectionCard title="Annual & Performance Reports" icon={FileBarChart2}>
        <ul className="divide-y divide-surface-hover">
          {annualReports.map((r) => (
            <ReportRowItem key={r.id} report={r} downloadingId={downloadingId} onDownload={handleDownload} />
          ))}
        </ul>
      </SectionCard>

      <p className="text-[11px] text-subtle flex items-center gap-1.5">
        <Info size={12} className="text-primary" />
        All figures are compiled and calculated by the Dhyana platform for reporting purposes only — investors cannot edit report data.
      </p>

      {toast && (
        <div className="fixed bottom-6 right-6 z-50 flex items-center gap-2 bg-surface border border-border rounded-xl px-4 py-3 shadow-lg max-w-sm">
          <CheckCircle2 size={16} className="text-sage shrink-0" />
          <p className="text-xs text-foreground">{toast}</p>
        </div>
      )}
    </div>
  );
}
